[package]
name = "vast-enum"
version = "0.1.0"
edition = "2018"

[dev-dependencies]
num_enum = "0.5"

[dependencies]
derivative = { version = "2", features = ["use_core"] }
serde = { version = "1", optional = true, default-features = false, features = ["derive"] }
